## Tensors
https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html

In [2]:
import torch
import numpy as np

In [ ]:
# Create tensor from regular lists
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
display(x_data)

tensor([[1, 2],
        [3, 4]])

In [7]:
# Create tensor from numpy arrays
np_array = np.array(data)
display(np_array)
x_np = torch.from_numpy(np_array)
display(x_np)

array([[1, 2],
       [3, 4]])

tensor([[1, 2],
        [3, 4]])

In [10]:
# Creating a tensor from another tensor (keep the same size)
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor:\n {x_ones}\n")
x_rand = torch.rand_like(x_data, dtype=torch.float) # Change data_type
print(f"Random Tensor:\n {x_rand}\n")

Ones Tensor:
 tensor([[1, 1],
        [1, 1]])

Random Tensor:
 tensor([[0.2394, 0.7395],
        [0.5584, 0.5068]])



In [ ]:
# Tensors are defined by their shape
# (2, 2) = 2 x 2 matrix
# (2, 3, 2) = 2 x 3 x 2 matrix (3D matrix)
shape = (2, 2)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[[1.0750e-01, 2.5355e-01, 5.6226e-02],
         [5.4371e-01, 9.8798e-02, 5.4700e-01]],

        [[4.7690e-01, 6.1404e-01, 1.9203e-01],
         [3.4612e-01, 5.5572e-01, 5.0008e-04]]]) 

Ones Tensor: 
 tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]) 

Zeros Tensor: 
 tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
